# Generated by Django 2.2.6 on 2019-11-15 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='suppliers',
            field=models.ManyToManyField(null=True, to='accounts.Supplier'),
        ),
    ]
