# Generated by Django 2.2.6 on 2019-11-15 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20191116_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='accepted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='suppliers',
            field=models.ManyToManyField(blank=True, null=True, to='accounts.Supplier'),
        ),
    ]
