# Generated by Django 2.2.6 on 2019-11-15 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20191116_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='suppliers',
            field=models.ManyToManyField(blank=True, to='accounts.Supplier'),
        ),
    ]
