# Generated by Django 2.2.6 on 2019-11-15 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_client_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='email',
            field=models.EmailField(default='test@testmail.com', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
