# Generated by Django 2.2.7 on 2020-02-23 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('document', models.FileField(blank=True, null=True, upload_to='documents/quotations/')),
                ('comments', models.TextField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
            options={
                'verbose_name': 'quotation',
                'verbose_name_plural': 'quotations',
            },
        ),
        migrations.CreateModel(
            name='InquirySheet',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('document', models.FileField(blank=True, null=True, upload_to='documents/inquiry_sheets/')),
                ('comments', models.TextField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
            options={
                'verbose_name': 'inquirysheet',
                'verbose_name_plural': 'inquirysheets',
            },
        ),
    ]
